name: CI

on: [push]

env:
  SNAKEMAKE_CONDA_PREFIX: /usr/share/miniconda/envs/
  
concurrency: 
  group: ${{ github.ref }}
  cancel-in-progress: true

  
jobs:     
  setup-conda-envs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          # List of files, dirs, etc. to cache:
          path: |
            /usr/share/miniconda/envs
            ~/.snakemake/conda/
          # key for restoring / saving cache:
          key: ${{ runner.os }}-conda-envs-${{hashFiles('workflow/envs/*.y*ml')}}
          restore-keys: |
            ${{ runner.os }}-conda-envs-
        id: cache
      
      - name: Setup mamba
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          # conda config --set channel_priority strict
          conda install -c conda-forge -q mamba
          # ensure that mamba is happy to write into the cache
          sudo chown -R runner:docker /usr/share/miniconda/pkgs/cache
        
      - name: Setup Snakemake environment
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          mamba env update -q --name macroconf_tests --file workflow/envs/test_environment.yml
          mamba env update -q --name snakemake --file workflow/envs/snakemake.yaml
          mamba env update -q --name stats --file workflow/envs/stats.yaml
        if: steps.cache.outputs.cache-hit != 'true'
        
      - name: Setup conda environments
        run: |
          # Create all required Snakemake conda environments
          # activate conda env
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate snakemake
          snakemake --conda-create-envs-only --use-conda -j2 --conda-frontend conda
        if: steps.cache.outputs.cache-hit != 'true'
          
      - name: List conda environments
        run: |
          conda env list

  formatting:
    runs-on: ubuntu-latest
    needs: setup-conda-envs
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup black environment
        run: |
          conda create -c conda-forge -y -q --name black black
          
      - name: Check formatting
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate black
          black --check --diff workflow/src workflow/tests workflow/scripts workflow/notebooks
      
      - name: Comment PR
        if: github.event_name == 'pull_request' && failure()
        uses: marocchino/sticky-pull-request-comment@v2.2.1
        with:
          message: 'Please format your code with [black](https://black.readthedocs.io): `black snakemake tests/*.py`.'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  testing:
    runs-on: ubuntu-latest
    needs: setup-conda-envs
    steps:
      - uses: actions/checkout@v3
      
      - name: Cache
        uses: actions/cache@v3.0.11
        with:
          # List of files, dirs, etc. to cache:
          path: |
            /usr/share/miniconda/envs
            ~/.snakemake/conda/
          # key for restoring / saving cache:
          key: ${{ runner.os }}-conda-envs-${{hashFiles('workflow/envs/*.y*ml')}}
        id: cache
      
      - name: Setup Snakemake environment
        run: |
          export PATH="/usr/share/miniconda/bin:$PATH"
          # conda config --set channel_priority strict
          conda install -c conda-forge -q mamba
          # ensure that mamba is happy to write into the cache
          sudo chown -R runner:docker /usr/share/miniconda/pkgs/cache
          mamba env update -q --name snakemake --file workflow/envs/test_environment.yml
          
      - name: Setup conda environments
        run: |
          # Create all required Snakemake conda environments
          # activate conda env
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate snakemake
          snakemake --conda-create-envs-only --use-conda -j2
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Run tests
        env:
          CI: true
        run: |
          # activate conda env
          export PATH="/usr/share/miniconda/bin:$PATH"
          source activate snakemake
          
          cd workflow
          pytest -v -x tests
